language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt && pip install -r requirements-dev.txt
script:
  - ./linters.sh && coverage run --source=flask_i18n/ setup.py test
after_success:
  - coveralls
